name: Basic CI Pipeline

# Trigger this pipeline on every push

on: [push]

jobs:
    builds:
        runs-on: ubuntu-latest

        steps:
            - name: Build Stage
              run: echo "Application build successfully"
            - name: Test Stage
              run: echo "Test Cases passed"
            - name: Build deploy
              run: echo "Application deplyed successfully"