name: 

on:
    push:
        branches: [ main ]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: build app
              run: echo "build done"
    test:
        runs-on: ubuntu-latest
        steps:
            - name: test app
              run: echo "test done"
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: deploy app
              run: echo "deploy done"
              